name: da
channels:
  - default
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - psycopg2
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - pip
  - requests